name: run-tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    strategy:
      matrix:
        php: [8.3, 8.2, 8.1, 8.0]
        laravel: [9.*, 10.*, 11.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench: 8.*
            carbon: ^3.0
          - laravel: 10.*
            testbench: 8.*
            carbon: ^2.63
          - laravel: 9.*
            testbench: 7.*
            carbon: ^2.63
        exclude:
          - laravel: 11.*
            php: [8.0, 8.1]
          - laravel: 10.*
            php: 8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run test suite
        run: composer test
